To: David Mazieres expires 2011-05-24 PDT <mazieres-rp7hejiukyxfxw8767ckpbtb5e@temporary-address.scs.stanford.edu>
Subject: Re: CS240H class stuff
From: David Terei <davidterei@gmail.com>
Delivered-To: mazieres-rp7hejiukyxfxw8767ckpbtb5e@temporary-address.scs.stanford.edu
Date: Wed, 23 Feb 2011 15:28:00 -0800

Looks good, pretty comprehensive and some nice guest lectures. Small
suggestions:

 - Might be nice to expand zipper lecture to be more general, to be
about purely functional data structures
 - Nice to cover the Data Parallel Haskell stuff in the parallelism
lecture (so DPH proper but also things like Repa and Vector which came
out of it)
 - Cover DSLs & EDSLs. (e.g maybe look at some of the GPU programming
libraries...)
 - Maybe a small coverage on some more theoretical stuff like
semantics and proofs just since students will come across that all the
time while browsing the net to learn haskell.

Cheers,
David
